service: discord-scheduler

org: apmabi
app: apmabi-lambda

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-2
  profile: apmabi
  memorySize: 128
  timeout: 10
  stage: prod # 기본 스테이지를 prod로 설정
  environment:
    DISCORD_WEBHOOK_URL: ${param:DISCORD_WEBHOOK_URL}
    # DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}

functions:
  scheduler:
    handler: src/handler.execute
    events:
      - schedule: cron(58 2/3 * * ? *)
      - cloudwatchEvent:
          event:
            # source:
            # - 'aws.ec2'
            # detail-type:
            # - 'EC2 Instance State-change Notification'
            detail:
              state:
                - pending
          enabled: false
